// gen-docs generates the CLI's documentation artefacts from the cobra
// command tree. Right now it emits man pages only, invoked from
// script/build.go's `manpages` task and (transitively) from goreleaser's
// `before` hook. See README's Available commands section for the wire
// contract each generated page covers.
//
//	go run ./cmd/gen-docs --man-page --doc-path ./share/man/man1/
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra/doc"
	"github.com/spf13/pflag"
	"github.com/vulncheck-oss/cli/pkg/cmd/root"
)

func main() {
	// Use a local FlagSet so our --man-page / --doc-path flags don't leak
	// into pflag.CommandLine — otherwise cobra picks them up and lists
	// them under "OPTIONS INHERITED FROM PARENT COMMANDS" on every man page.
	fs := pflag.NewFlagSet("gen-docs", pflag.ExitOnError)
	manPage := fs.Bool("man-page", false, "Generate man pages under --doc-path")
	docPath := fs.String("doc-path", "", "Output directory (required)")
	if err := fs.Parse(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "gen-docs: %v\n", err)
		os.Exit(2)
	}

	if *docPath == "" {
		fmt.Fprintln(os.Stderr, "gen-docs: --doc-path is required")
		os.Exit(2)
	}

	abs, err := filepath.Abs(*docPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-docs: resolve --doc-path: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(abs, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "gen-docs: mkdir %s: %v\n", abs, err)
		os.Exit(1)
	}

	cmd := root.NewCmdRoot()
	// The auto-generated "Auto generated by spf13/cobra on <date>" footer
	// would cause a fresh diff on every rebuild; suppress it so release
	// artefacts stay reproducible.
	cmd.DisableAutoGenTag = true

	if *manPage {
		header := &doc.GenManHeader{
			Title:   "VULNCHECK",
			Section: "1",
			Source:  "VulnCheck CLI",
			Manual:  "VulnCheck CLI Manual",
		}
		if err := doc.GenManTree(cmd, header, abs); err != nil {
			fmt.Fprintf(os.Stderr, "gen-docs: GenManTree: %v\n", err)
			os.Exit(1)
		}
		return
	}

	fmt.Fprintln(os.Stderr, "gen-docs: nothing to do (pass --man-page)")
	os.Exit(2)
}
