name: No go-ray check

on:
  push:
    paths: [go.mod]
  pull_request:
    paths: [go.mod]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if grep -q "github.com/octoper/go-ray" go.mod; then
            echo "Error: go-ray found in go.mod"
            exit 1
          fi
